### ISSUE TITLE
Cannot `rake db:seed`

### ISSUE THREAD

**Issue by MikeMcQuaid** [koraktor/braumeister.org#47]
I've setup the project using my script in https://github.com/koraktor/braumeister.org/pull/46 based on my best understanding from the documentation of the requirements. With a clean MongoDB (i.e. run `rm -rf /usr/local/var/mongodb/; brew services stop mongodb@3.2; brew reinstall mongodb@3.2; mkdir -p /usr/local/var/mongodb/; brew services restart mongodb@3.2`) and running `script/bootstrap` then `rake db:seed` does not succeed:
```
rake aborted!
NoMethodError: undefined method `refresh' for #<Repository:0x007fa613d98328>
/Users/mike/Documents/braumeister.org/db/seeds.rb:25:in `block in <top (required)>'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/contextual/mongo.rb:696:in `yield_document'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/contextual/mongo.rb:133:in `block in each'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:45:in `block in each'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `block in each'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `each'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `each'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:44:in `each'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/query_cache.rb:222:in `each'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/contextual/mongo.rb:132:in `each'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/contextual.rb:20:in `each'
/Users/mike/Documents/braumeister.org/db/seeds.rb:24:in `<top (required)>'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/railties/database.rake:20:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

If it run it again immediately I get a different error:
```
rake aborted!
Mongo::Error::OperationFailure: E11000 duplicate key error collection: braumeister.repositories index: _id_ dup key: { : "Homebrew/brew" } (11000)
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongo-2.4.1/lib/mongo/operation/result.rb:256:in `validate!'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongo-2.4.1/lib/mongo/operation/write/insert.rb:55:in `execute_write_command'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongo-2.4.1/lib/mongo/operation/write/write_command_enabled.rb:41:in `execute'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongo-2.4.1/lib/mongo/collection.rb:365:in `block in insert_one'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongo-2.4.1/lib/mongo/retryable.rb:112:in `write_with_retry'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongo-2.4.1/lib/mongo/collection.rb:356:in `insert_one'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/query_cache.rb:182:in `insert_one_with_clear_cache'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/persistable/creatable.rb:79:in `insert_as_root'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/persistable/creatable.rb:27:in `block in insert'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/persistable/creatable.rb:118:in `block (2 levels) in prepare_insert'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:126:in `call'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:455:in `call'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_create_callbacks'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/interceptable.rb:138:in `run_callbacks'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/persistable/creatable.rb:117:in `block in prepare_insert'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:126:in `call'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:455:in `call'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/interceptable.rb:138:in `run_callbacks'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/persistable/creatable.rb:116:in `prepare_insert'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/persistable/creatable.rb:23:in `insert'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/persistable/savable.rb:23:in `save'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/persistable/creatable.rb:149:in `block in create'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/threaded/lifecycle.rb:161:in `_creating'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/persistable/creatable.rb:144:in `create'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/criteria/modifiable.rb:185:in `create_document'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/criteria/modifiable.rb:36:in `create'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/criteria/modifiable.rb:200:in `find_or'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/criteria/modifiable.rb:80:in `find_or_create_by'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/findable.rb:15:in `find_or_create_by'
/Users/mike/Documents/braumeister.org/db/seeds.rb:10:in `<top (required)>'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
/Users/mike/Documents/braumeister.org/vendor/ruby/gems/mongoid-6.1.0/lib/mongoid/railties/database.rake:20:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

This seems similar to https://github.com/koraktor/braumeister.org/issues/33 which was previously fixed. I wonder if there's a way to add a slimmer `rake db:seed` to CI to avoid this breaking in future?

**Comment by MikeMcQuaid** [comment]
Thanks @koraktor!

**Comment by koraktor** [comment]
Thanks for the hint. This was broken by recent changes and I didn’t had an eye on this one.

**Comment by MikeMcQuaid** [comment]
@koraktor Any way this could go into something Travis CI runs?

**Comment by koraktor** [comment]
@MikeMcQuaid Not as-is, it really imports everything it can – so it takes a long time to run. I’ll have a look on how to test this and maybe other Rake tasks.
